name: Build

on:
  workflow_dispatch:
    inputs:
      library:
        description: "Name of the library to build"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ inputs.project }}
