name: Projects

on:
  push:
    tags: ["v*.*.*"]
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "projects/**"

jobs:
  projects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Projects
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const workflow_id = 'build.yml';
            
            let branchOrTag;
            if (github.event_name === 'pull_request') {
              branchOrTag = github.event.pull_request.head.ref;
            } else {
              branchOrTag = github.context.ref.startsWith('refs/tags/') ? github.context.ref.replace('refs/tags/', '') : github.context.ref;
            }

            console.log(owner);
            console.log(repo);
            console.log(workflow_id);
            console.log(branchOrTag);

            const projects = require('./angular.json').projects;
            const libraries = Object.keys(projects).filter(name => projects[name].projectType === 'library').join(' ');
            console.log(libraries);

            for (const library of libraries.split(' ')) {
              await github.rest.actions.createWorkflowDispatch({
                owner,
                repo,
                workflow_id,
                ref: branchOrTag,
                inputs: {
                  library: library,
                },
              });
            }
