name: Projects

on:
  push:
    tags: ["v*.*.*"]
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "projects/**"

jobs:
  projects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Projects
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            const repoInfo = await github.repos.get({owner: context.repo.owner, repo: context.repo.repo});
            const owner = repoInfo.data.owner.login;
            const repo = repoInfo.data.name;
            const workflow_id = 'build';
            const ref = github.context.ref;
            const branchOrTag = ref.startsWith('refs/tags/') ? ref.replace('refs/tags/', '') : ref;

            console.log(owner);
            console.log(repo);
            console.log(workflow_id);
            console.log(branchOrTag);

            const projects = require('./angular.json').projects;
            const libraries = Object.keys(projects).filter(name => projects[name].projectType === 'library').join(' ');
            console.log(libraries);

            for (const library of libraries.split(' ')) {
              await github.rest.actions.createWorkflowDispatch({
                owner,
                repo,
                workflow_id,
                ref,
                inputs: {
                  library: library,
                },
              });
            }
