name: Projects

on:
  push:
    tags: ["v*.*.*"]
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "projects/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Projects
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const workflow_id = 'build';
            const ref = github.context.ref;
            const branchOrTag = ref.startsWith('refs/tags/') ? ref.replace('refs/tags/', '') : ref;


            console.log(owner);
            console.log(repo);
            console.log(workflow_id);
            console.log(branchOrTag);

            const projects = require('./angular.json').projects;
            const libraries = Object.keys(projects).filter(name => projects[name].projectType === "library").join(' ');
            console.log(libraries);

            for library in $libraries; do
              github.rest.actions.createWorkflowDispatch({
                owner,
                repo,
                workflow_id,
                ref,
              });
            done
